---
output: html_document
---



<!-- ### Intern Profiles -->
<!-- ```{r, echo=FALSE, results='asis'} -->
<!-- profile<-lake1[lake1$INFO_TYPE=="DP",] -->
<!-- profile<-unique(profile[c('LAKE_ID','LOCATION_ID','Characteristic.Name','Depth','Result.Value','SAMPLE_DATE')]) -->
<!-- profile$Characteristic.Name[profile$Characteristic.Name==""] <- NA -->
<!-- profile<-profile[!is.na(profile$Characteristic.Name),] -->
<!-- if((length(profile$Result.Value))!=0){ -->
<!-- library(ggplot2) -->
<!--   library(gridExtra) -->
<!-- params<-unique(profile$Characteristic.Name) -->
<!-- nparams<-length(params) -->
<!-- p<-list() -->
<!-- for(i in 1:nparams){ -->
<!--   profile1<-profile[profile$Characteristic.Name==params[i],] -->
<!--   profile1<-profile1[!is.na(profile1$Characteristic.Name),] -->
<!--   profile1<-profile1[order(profile1$SAMPLE_DATE,profile1$Depth),] -->
<!--   profile1$SAMPLE_DATE<-format(profile1$SAMPLE_DATE,"%Y.%m.%d") -->
<!--   profile1$SAMPLE_DATE<-factor(profile1$SAMPLE_DATE,unique(profile1$SAMPLE_DATE)) -->
<!--  ggplot(profile1[order(profile1$Depth,profile1$SAMPLE_DATE),],aes(Result.Value,Depth)) + -->
<!--     geom_point() + -->
<!--     geom_path(aes(color=factor(SAMPLE_DATE))) + -->
<!--     scale_y_reverse(lim = c((max(profile$Depth)+0.25),0)) + -->
<!--     theme(axis.title.x = element_blank()) + -->
<!--     labs(title=params[i], y="Depth (m)",colour = "") -->
<!--   rm(list=c('profile1')) -->
<!-- } -->
<!-- } -->

<!-- ``` -->

### `r titles[1]` Long-Term Trend Analysis

#### Clarity
```{r secchi, echo=FALSE, message=FALSE, warning=FALSE}
#limiting data to only secchi records
secchi_longterm <- lake1 %>% 
  filter(Characteristic.Name == "DEPTH, SECCHI DISK DEPTH")

secchi_longterm$year <- as.numeric(format(as.Date(secchi_longterm$SAMPLE_DATE), format = "%Y"))
secchi_longterm$Result.Value <- as.numeric(secchi_longterm$Result.Value)

if(nrow(secchi_longterm) > 0){
secchi_longterm <- secchi_longterm %>% 
  group_by(year) %>% 
  summarize(avg_clarity= mean(Result.Value))  %>% 
  mutate(image = "C:/Users/amtweitm/OneDrive - New York State Office of Information Technology Services/Documents/R/CSLAP_reporting/images/sec.png")

#removing NAs
secchi_longterm <- na.omit(secchi_longterm)

#creating variable  adjusting y axis based on max secchi
yaxis <- max(max(secchi_longterm$avg_clarity), 7)
yaxis <- round(yaxis)

#figure
ggplot(data=secchi_longterm, aes(x=as.numeric(year), y=as.numeric(avg_clarity))) + 
  scale_y_continuous(trans="reverse", limits=c(yaxis,0), expand = c(0,0)) +
  geom_point() +
  theme_classic() +
  scale_x_continuous(position = "top", limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  geom_segment(aes(xend=year), yend=0, size=1) +
  geom_image(aes(image=image), size=.05) +
  ylab("Average Summer Water Clarity (m)") +
  xlab("") +
  geom_hline(yintercept = 2, linetype="dashed") +
  geom_hline(yintercept = 5, linetype="dashed") +
  annotate(geom="label", x=1990, y=1, label="Eutrophic",
              color="black", alpha=0.9) +
  annotate("label", x=1990, y=3.5, label="Mesotrophic",
              color="black", alpha=0.9) +
  annotate("label", x=1990, y=6, label="Oligotrophic",
              color="black", alpha=0.9)
}
  
```

#### Chlorophyll *a*

```{r chlor-a, echo=FALSE, message=FALSE, warning=FALSE}
#avg summer chla is calculated by averaging SUMMER (jun1-jul15,sep15-oct1) and HIGH PRODUCTIVITY (jul15-sep15) separately and then averaging the two averages


#limiting data to only chl a records
chla_longterm <- lake1 %>% 
  filter(Characteristic.Name == "CHLOROPHYLL A")

if(nrow(chla_longterm) > 0){

chla_longterm$Result.Value <- as.numeric(chla_longterm$Result.Value)
chla_longterm$year <- as.numeric(chla_longterm$year)


chla_longterm <- chla_longterm %>% 
  group_by(year) %>% 
  summarize(avg_chla = mean(Result.Value)) 

chla_longterm <- na.omit(chla_longterm)

if(max(chla_longterm$avg_chla)<12){
      ggplot(data=chla_longterm) +
      geom_col(aes(x=year,y=avg_chla), fill="green") +
      theme_classic() +
      geom_hline(yintercept = 2, linetype="dashed") +
      geom_hline(yintercept = 8, linetype="dashed") +
      annotate(geom="label", x=1990, y=1, label="Oligotrophic",
              color="black", alpha=0.9) +
      annotate(geom="label", x=1990, y=5, label="Mesotrophic",
              color="black") +
      annotate(geom="label", x=1990, y=10, label="Eutrophic",
              color="black", alpha=0.9) +
      scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
      scale_y_continuous(expand = c(0,0), limits=c(0,12), labels = scales::label_comma()) +
      ylab("Average Summer Chl.a (ug/L)") +
      xlab("")
} else if(max(chla_longterm$avg_chla)<30 & max(chla_longterm$avg_chla)>12){
      ggplot(data=chla_longterm) +
      geom_col(aes(x=year,y=avg_chla), fill="green") +
      theme_classic() +
      geom_hline(yintercept = 2, linetype="dashed") +
      geom_hline(yintercept = 8, linetype="dashed") +
      annotate(geom="label", x=1990, y=1, label="Oligotrophic",
              color="black", alpha=0.9) +
      annotate(geom="label", x=1990, y=5, label="Mesotrophic",
              color="black", alpha=0.9) +
      annotate(geom="label", x=1990, y=10, label="Eutrophic",
              color="black", alpha=0.9) +
      scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
      scale_y_continuous(expand = c(0,0), limits=c(0,NA), labels = scales::label_comma()) +
      ylab("Average Summer Chl.a (ug/L)") +
      xlab("")
  } else if(max(chla_longterm$avg_chla)>=30 & max(chla_longterm$avg_chla)<200){
      ggplot(data=chla_longterm) +
      geom_col(aes(x=year,y=avg_chla), fill="green") +
      theme_classic() +
      geom_hline(yintercept = 2, linetype="dashed") +
      geom_hline(yintercept = 8, linetype="dashed") +
      annotate(geom="label", x=1990, y=5, label="Mesotrophic",
              color="black", alpha=0.9) +
      annotate(geom="label", x=1990, y=15, label="Eutrophic",
              color="black", alpha=0.9) +
      scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
      scale_y_continuous(expand = c(0,0), limits=c(0,NA), labels = scales::label_comma()) +
      ylab("Average Summer Chl.a (ug/L)") +
      xlab("")
  } else if(max(chla_longterm$avg_chla)>200){
      ggplot(data=chla_longterm) +
      geom_col(aes(x=year,y=avg_chla), fill="green") +
      theme_classic() +
      geom_hline(yintercept = 8, linetype="dashed") +
      annotate(geom="label", x=1990, y=40, label="Eutrophic",
              color="black", alpha=0.9) +
      scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), 
                     breaks=seq(0, round_5yrs(report_year), by = 5)) +
      scale_y_continuous(expand = c(0,0), limits=c(0,NA), labels = scales::label_comma()) +
      ylab("Average Summer Chl.a (ug/L)") +
      xlab("")
  }
}
```

#### Surface and Deep Phosphorus
```{r phos, echo=FALSE, message=FALSE, warning=FALSE}
#avg summer phos is calculated by averaging SUMMER (jun1-jul15,sep15-oct1) and HIGH PRODUCTIVITY (jul15-sep15) separately and then averaging the two averages
#limiting data to only phos records and getting rid of D phosphorous
phos_longterm <- lake1 %>% 
  filter(Characteristic.Name == "PHOSPHORUS") %>% 
  filter(Result.Sample.Fraction != "D")


if(nrow(phos_longterm) > 0){
phos_longterm$year <- as.numeric(format(as.Date(phos_longterm$SAMPLE_DATE), format = "%Y"))
phos_longterm$Result.Value <- as.numeric(phos_longterm$Result.Value)

phos_longterm <- phos_longterm %>% 
  filter(!is.na(Result.Value)) %>% 
  group_by(INFO_TYPE, year) %>% 
  summarize(avg_phos = mean(Result.Value))

if(max(phos_longterm$avg_phos)<1){
  ggplot(data=phos_longterm) +
  geom_line(aes(x=year, y=avg_phos, color=INFO_TYPE)) +
  geom_point(aes(x=year, y=avg_phos, color=INFO_TYPE, shape=INFO_TYPE)) +
  scale_x_continuous(limits=c(1985, round_5yrs(report_year)+1), 
                     breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(limits=c(0.001, 1), expand = c(0,0), trans='log10', 
                     breaks=c(0.001,.01,0.02,0.1,0.5,1), labels = scales::label_comma()) +
  theme_classic() +
  geom_hline(yintercept = 0.01, linetype="dashed") +
  geom_hline(yintercept = 0.02, linetype="dashed") +
  annotate(geom="label", x=1990, y=0.005, label="Oligotrophic",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1990, y=0.015, label="Mesotrophic",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1990, y=0.04, label="Eutrophic",
              color="black", alpha=0.9) +
  ylab("Average Summer TP (mg/L)") +
  xlab("") +
  scale_color_manual(name="",
                    breaks = c("BS", "OW"),
                    values=c("red", "blue"),
                    labels = c("Deep", "Surface")) +
  scale_shape_manual(values=c(19,15)) +
  guides(shape=FALSE)
} else if(max(phos_longterm$avg_phos)>=1){
  ggplot(data=phos_longterm) +
  geom_line(aes(x=year, y=avg_phos, color=INFO_TYPE)) +
  geom_point(aes(x=year, y=avg_phos, color=INFO_TYPE, shape=INFO_TYPE)) +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), 
                     breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(limits=c(0.001, 10), expand = c(0,0), trans='log10',
                     breaks=c(0.001,0.01,0.02,1,10), labels = scales::label_comma()) +
  theme_classic() +
  geom_hline(yintercept = 0.01, linetype="dashed") +
  geom_hline(yintercept = 0.02, linetype="dashed") +
  annotate(geom="label", x=1990, y=0.005, label="Oligotrophic",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1990, y=0.015, label="Mesotrophic",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1990, y=0.04, label="Eutrophic",
              color="black", alpha=0.9) +
  ylab("Average Summer TP (mg/L)") +
  xlab("") +
  scale_color_manual(name="",
                    breaks = c("BS", "OW"),
                    values=c("red", "blue"),
                    labels = c("Deep", "Surface")) +
  scale_shape_manual(values=c(19,15)) +
  guides(shape=FALSE)
}
}



```

#### Nitrogen

```{r nitrogen, echo=FALSE, message=FALSE, warning=FALSE}
#max is 7.08
#limiting data to only nitrogen records
nitr_longterm <- lake1 %>% 
  filter(Characteristic.Name == "NITROGEN, TOTAL" | 
        Characteristic.Name == "AMMONIA" | 
        Characteristic.Name == "NITROGEN, NITRATE-NITRITE") %>% 
  filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
nitr_longterm$year <- as.numeric(format(as.Date(nitr_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
nitr_longterm$Result.Value <- as.numeric(nitr_longterm$Result.Value)

#summarizing the average nitrogen reading for each year
nitr_longterm <- nitr_longterm %>% 
  group_by(Characteristic.Name, year) %>% 
  summarize(avg_nitr = mean(Result.Value)) %>% 
  filter(avg_nitr != "NA")

yaxis <- max(nitr_longterm$avg_nitr) * 10

ggplot(data=nitr_longterm) +
  geom_line(aes(x=year, y=avg_nitr, color=Characteristic.Name)) +
  geom_point(aes(x=year, y=avg_nitr, color=Characteristic.Name, shape=Characteristic.Name)) +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(limits=c(0.001,yaxis), expand = c(0,0), trans='log10', 
                     breaks=c(0.001,0.01,0.1,1, round(yaxis)),
                     labels = scales::label_comma()) +
  theme_classic() +
  ylab("Average Summer Nitrogen (mg/L)") +
  xlab("") +
  scale_color_manual(name="",
                    breaks = c("NITROGEN, TOTAL", "AMMONIA", "NITROGEN, NITRATE-NITRITE"),
                    values=c("green", "red", "blue"),
                    labels = c("TN", "NH3", "NOx")) +
  scale_shape_manual(values=c(19,15,17)) +
  guides(shape=FALSE)


```

#### TN : TP

```{r tn-tp, echo=FALSE, message=FALSE, warning=FALSE}
#creating separate n and p dfs, joining by sample, '
#calculating ratio for each sample and then calculating average ratio for each year

nitr <- lake1 %>% 
  filter(Characteristic.Name == "NITROGEN, TOTAL") %>% 
  rename(nitrogen = Result.Value) %>% 
  filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d")) %>% 
  select(SAMPLE_NAME, SAMPLE_DATE, nitrogen, year)

phos <- lake1 %>% 
 filter(Characteristic.Name == "PHOSPHORUS" & Result.Sample.Fraction != "D") %>% 
  rename(phosphorus = Result.Value) %>% 
  filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d")) %>% 
  select(SAMPLE_NAME, SAMPLE_DATE, phosphorus, year)

np_bysamp <- full_join(nitr, phos) %>% 
  mutate(tntp = as.numeric(nitrogen)/as.numeric(phosphorus)) 

np_bysamp <- na.omit(np_bysamp)
  
tntp_longterm <- np_bysamp %>% 
  group_by(year) %>% 
  summarize(avg_tntp = mean(tntp))

tntp_longterm$year <- as.numeric(tntp_longterm$year)

if(nrow(tntp_longterm) != 0){
ggplot(data=tntp_longterm) +
  geom_col(aes(x=year, y=avg_tntp))+
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(expand = c(0,0), trans='log10', 
                     limits=c(1,1000), labels = scales::label_comma()) +
  theme_classic() +
  ylab("Average Summer TN:TP") +
  xlab("") +
  geom_hline(yintercept = 10, linetype="dashed") +
  geom_hline(yintercept = 20, linetype="dashed") +
  annotate(geom="label", x=1991, y=3, label="Nitrogen Limited",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1991, y=14, label="N or P Limited",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1991, y=75, label="Phosphorus Limited",
              color="black", alpha=0.9) +
  annotate("segment", x = 1985, xend = 1985, y = 30, yend = 135, arrow=arrow()) +
  annotate("segment", x = 1985, xend = 1985, y = 7, yend = 1.5, arrow=arrow())
}
```

#### pH

```{r ph, echo=FALSE, message=FALSE, warning=FALSE}

#limiting data to only pH records
ph_longterm <- lake1 %>% 
  filter(Characteristic.Name == "PH") %>% 
  filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
ph_longterm$year <- as.numeric(format(as.Date(ph_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
ph_longterm$Result.Value <- as.numeric(ph_longterm$Result.Value)

#summarizing the avergae ph reading for each year
ph_longterm <- ph_longterm %>% 
  group_by(Characteristic.Name, year) %>% 
  summarize(avg_ph = mean(Result.Value)) 

#defining most recent year

ggplot(data=ph_longterm) +
    geom_line(aes(x=year, y=avg_ph), color="blue") +
  geom_point(aes(x=year, y=avg_ph),color="blue", shape=15) +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(expand = c(0,0), limits=c(4,10)) +
  theme_classic() +
  ylab("Average Summer pH") +
  xlab("") +
  geom_hline(yintercept = 6.5, linetype="dashed") +
  geom_hline(yintercept = 7.5, linetype="dashed") +
  geom_hline(yintercept = 8.5, linetype="dashed") +
  annotate(geom="label", x=1995, y=5.75, label="Acidic (Below NYS WQ standard)",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1995, y=7, label="Circumneutral (Acceptable)",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1995, y=8, label="Slightly Alkaline (Acceptable)",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1995, y=9.25, label="Highly Alkaline (Above NYS WQ standard)",
              color="black", alpha=0.9) 

```

#### Specific Conductance

```{r specific-cond, echo=FALSE, message=FALSE, warning=FALSE}
#limiting data to only summer conductance records
cond_longterm <- lake1 %>% 
  filter(Characteristic.Name == "SPECIFIC CONDUCTANCE") %>% 
  filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
cond_longterm$year <- as.numeric(format(as.Date(cond_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
cond_longterm$Result.Value <- as.numeric(cond_longterm$Result.Value)

#summarizing the average conductance reading for each year
cond_longterm <- cond_longterm %>% 
  group_by(year) %>% 
  summarize(avg_cond = mean(Result.Value)) 

#defining most recent year
cond_longterm <- na.omit(cond_longterm)

yaxis <- max(400, max(cond_longterm$avg_cond))

ggplot(data=cond_longterm) +
  geom_col(aes(x=year,y=avg_cond), fill="blue") +
  theme_classic() +
  geom_hline(yintercept = 125, linetype="dashed") +
  geom_hline(yintercept = 250, linetype="dashed") +
  annotate(geom="label", x=1990, y=75, label="Softwater",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1990, y=300, label="Hardwater",
              color="black", alpha=0.9) +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(expand = c(0,0), limits=c(0,yaxis), labels = scales::label_comma()) +
  ylab("Average Summer Conductivity (uS/cm)") +
  xlab("")


```

#### Calcium

```{r calcium, echo=FALSE, message=FALSE, warning=FALSE}
#limiting data to only calcium records

calc_longterm <- lake1 %>% 
  filter(Characteristic.Name == "CALCIUM") %>% 
  filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
calc_longterm$year <- as.numeric(format(as.Date(calc_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
calc_longterm$Result.Value <- as.numeric(calc_longterm$Result.Value)

#summarizing the average calcium reading for each year
calc_longterm <- calc_longterm %>% 
  group_by(year) %>% 
  summarize(avg_calc = mean(Result.Value)) 

#defining most recent year
calc_longterm <- na.omit(calc_longterm)

yaxis <- max(30, max(calc_longterm$avg_calc))

if(nrow(calc_longterm) != "0"){
ggplot(data=calc_longterm) +
  geom_col(aes(x=year,y=avg_calc), fill="blue") +
  theme_classic() +
  geom_hline(yintercept = 10, linetype="dashed") +
  geom_hline(yintercept = 20, linetype="dashed") +
  annotate(geom="label", x=1993, y=5, label="Not Susceptible to Zebra Mussels",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1993, y=15, label="May Be Susceptible to Zebra Mussels",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1993, y=25, label="Highly Susceptible to Zebra Mussels",
              color="black", alpha=0.9) +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(expand = c(0,0), limits=c(0,yaxis)) +
  ylab("Average Summer Calcium (mg/L)") +
  xlab("")
}

```

#### Chloride

```{r chloride, echo=FALSE, message=FALSE, warning=FALSE}
#limiting data to only chloride records
#0 to 326
chlor_longterm <- lake1 %>% 
  filter(Characteristic.Name == "CHLORIDE") %>% 
 filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
chlor_longterm$year <- as.numeric(format(as.Date(chlor_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
chlor_longterm$Result.Value <- as.numeric(chlor_longterm$Result.Value)

#summarizing the average chlroide reading for each year
chlor_longterm <- chlor_longterm %>% 
  group_by(year) %>% 
  summarize(avg_chlor = mean(Result.Value)) 

#defining most recent year

ggplot(data=chlor_longterm) +
  geom_col(aes(x=year,y=avg_chlor), fill="blue") +
  theme_classic() +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(expand = c(0,0)) +
  ylab("Average Summer Chloride (mg/L)") +
  xlab("")


```

#### Color

```{r color, echo=FALSE, message=FALSE, warning=FALSE}
#limiting data to only color records
#0 to 289
color_longterm <- lake1 %>% 
  filter(Characteristic.Name == "TRUE COLOR") %>% 
 filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
color_longterm$year <- as.numeric(format(as.Date(color_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
color_longterm$Result.Value <- as.numeric(color_longterm$Result.Value)

#summarizing the average color reading for each year
color_longterm <- color_longterm %>% 
  group_by(year) %>% 
  summarize(avg_color = mean(Result.Value)) 

#removing NAs
color_longterm <- na.omit(color_longterm)

yaxis <- max(50, max(color_longterm$avg_color))

ggplot(data=color_longterm) +
  geom_col(aes(x=year,y=avg_color), fill="blue") +
  theme_classic() +
  geom_hline(yintercept = 10, linetype="dashed") +
  geom_hline(yintercept = 30, linetype="dashed") +
  annotate(geom="label", x=1993, y=5, label="Uncolored",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1993, y=20, label="Weakly Colored",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1993, y=40, label="Colored",
              color="black", alpha=0.9) +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(expand = c(0,0), limits=c(0,yaxis)) +
  ylab("Average Summer Color (color units)") +
  xlab("")


```

#### Surface and Deep Temperature

```{r temp, echo=FALSE, message=FALSE, warning=FALSE}
#limiting data to only temp records
temp_longterm <- lake1 %>% 
  filter(Characteristic.Name == "TEMPERATURE, WATER") %>% 
 filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
temp_longterm$year <- as.numeric(format(as.Date(temp_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
temp_longterm$Result.Value <- as.numeric(temp_longterm$Result.Value)

#summarizing the avergae temp reading for each year
temp_longterm <- temp_longterm %>% 
  group_by(Characteristic.Name, year, INFO_TYPE) %>% 
  summarize(avg_temp = mean(Result.Value)) 

#defining most recent year

ggplot(data=temp_longterm) +
    geom_line(aes(x=year, y=avg_temp, color=INFO_TYPE)) +
  geom_point(aes(x=year, y=avg_temp, color=INFO_TYPE, shape=INFO_TYPE)) +
  scale_x_continuous(limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(expand = c(0,0), limits=c(1,40)) +
  theme_classic() +
  ylab("Avg Summer Water Temp (C)") +
  xlab("") +
  scale_color_manual(name="",
                    breaks = c("OW", "BS"),
                    values=c("blue", "red"),
                    labels = c("Surface", "Deep")) +
  scale_shape_manual(values=c(15,19)) +
  guides(shape=FALSE)
```

#### Lake Perception

```{r lake-percep, echo=FALSE, message=FALSE, warning=FALSE}
#limiting data to only perception records
#QA is clarity
#QB is plant coverage
#QC recreation
percep_longterm <- lake1 %>% 
  filter(Characteristic.Name == "QA" | 
        Characteristic.Name == "QB" | 
        Characteristic.Name == "QC") %>% 
 filter(SAMPLE_DATE >= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      06, 01, sep = "-"), format= "%Y-%m-%d")) %>%
  filter(SAMPLE_DATE <= as.Date(paste(year(as.Date(SAMPLE_DATE)), 
                                      10, 01, sep = "-"), format= "%Y-%m-%d"))

#pulling out the year and making it a number 
percep_longterm$year <- as.numeric(format(as.Date(percep_longterm$SAMPLE_DATE), format = "%Y"))

#making the result value a number instead of character
percep_longterm$Result.Value <- as.numeric(percep_longterm$Result.Value)

#summarizing the avergae nitrogen reading for each year
percep_longterm <- percep_longterm %>% 
  group_by(Characteristic.Name, year) %>% 
  summarize(avg_percep = mean(Result.Value)) 

#defining most recent year
ggplot(data=percep_longterm) +
    geom_line(aes(x=year, y=avg_percep, color=Characteristic.Name)) +
  geom_point(aes(x=year, y=avg_percep, color=Characteristic.Name, shape=Characteristic.Name)) +
  scale_x_continuous(position = "top",limits=c(1985,round_5yrs(report_year)+1), breaks=seq(0, round_5yrs(report_year), by = 5)) +
  scale_y_continuous(trans="reverse", expand = c(0,0), limits=c(6,0), labels = NULL, breaks = NULL) +
  theme_classic() +
  ylab("Avg Summer Lake Perception") +
  xlab("") +
  scale_color_manual(name="",
                    breaks = c("QA", "QB", "QC"),
                    values=c("blue", "green", "red"),
                    labels = c("Clarity", "Plant Coverage", "Recreation")) +
  scale_shape_manual(values=c(15,17,19)) +
  guides(shape=FALSE) +
  geom_hline(yintercept = 2, linetype="solid") +
  geom_hline(yintercept = 4, linetype="solid") +
  annotate(geom="label", x=1993, y=1, label="Subsurface Weeds/Clear Water",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1993, y=3, label="Surface Weeds/Algal Color Present",
              color="black", alpha=0.9) +
  annotate(geom="label", x=1993, y=5, label="Dense Weeds/Severely High Algae",
              color="black", alpha=0.9)


```

